name: FullSync Notion Star

on:
  workflow_dispatch:

jobs:
  full-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    steps:
      - uses: actions/checkout@v4  # 从 v2 升级到 v4

      - name: Setup environment
        uses: actions/setup-node@v4  # 从 v2.2.0 升级到 v4
        with:
          node-version: 16.x
          cache: 'yarn'  # 添加引号以确保正确解析

      - run: yarn

      - name: Run Full Sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
          FULLSYNC_LIMIT: 2000
          PARTIALSYNC_LIMIT: 10
          REPO_TOPICS_LIMIT: 50
          FULL_SYNC: 'true'  # 添加引号以确保布尔值正确传递
        run: npm start
