name: FullSync Notion Star

on:
  workflow_dispatch:

jobs:
  full-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
      FULLSYNC_LIMIT: 2000
      PARTIALSYNC_LIMIT: 10
      REPO_TOPICS_LIMIT: 50
      FULL_SYNC: 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Debug Environment Variables
        run: |
          echo "TOKEN_OF_GITHUB length: ${#TOKEN_OF_GITHUB}"
          echo "NOTION_API_KEY length: ${#NOTION_API_KEY}"
          echo "NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}"

      - run: yarn

      - name: Create cache directory
        run: mkdir -p .cache && echo "{}" > .cache/notion-page.json

      - name: Run Full Sync
        run: npm start
