name: Partial Sync Notion Star

on:
  schedule:
    - cron: '0 21 * * *' # UTC时间每天21:00（即北京时间次日5:00）
      timezone: 'Asia/Shanghai' # 指定时区为北京时间
  workflow_dispatch:
jobs:
  partial-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    steps:
      - uses: actions/checkout@v4

      - name: Download cache storage of last build
        uses: dawidd6/action-download-artifact@v4
        continue-on-error: true
        with:
          workflow: partial-sync.yml
          workflow_conclusion: success
          name: notion-sync-storage
          path: .cache

      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          always-auth: false
          node-version: 16.x
          cache: yarn

      - run: yarn

      - name: Run Partial Sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
          FULLSYNC_LIMIT: 2000
          PARTIALSYNC_LIMIT: 10
          REPO_TOPICS_LIMIT: 50
        run: npm start

      - uses: actions/upload-artifact@v4
        with:
          name: notion-sync-storage
          path: .cache
